trigger:
- develop
- qa
- prod
- main

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if endsWith(variables['Build.SourceBranchName'], 'develop') }}:
    stage: 'dev'
    credentials: 'AWS_TESTIGOS_ELECTORALES_DES_QA'
  ${{ if endsWith(variables['Build.SourceBranchName'], 'qa') }}:
    stage: 'qa'
    credentials: 'AWS_TESTIGOS_ELECTORALES_DES_QA'
  ${{ if not(or(endsWith(variables['Build.SourceBranchName'], 'develop'), endsWith(variables['Build.SourceBranchName'], 'qa'))) }}:
    stage: 'prod'
    credentials: 'AWS_TESTIGOS_ELECTORALES_PROD'

resources:
  repositories:
    - repository: templates
      type: git
      name: Infraestructura-DevOps/devops_util_pipeline

stages:
- stage: Analyse
  jobs:
  - job: maven
    steps:

    - template: steps-docker-ecr.yml@templates
      parameters:
        AWS_CREDENTIALS: $(credentials)
        DOCKER_PATH: '$(Build.SourcesDirectory)/Dockerfile'
        REPOSITORY_NAME: '$(stage)-ms-frontdsh-actores-v1'
        AWS_REGION: $(AWS_REGION)
    - task: AWSCLI@1
      inputs:
        awsCredentials: $(credentials)
        regionName: 'us-east-1'
        awsCommand: 'ecs'
        awsSubCommand: 'update-service'
        awsArguments: '--cluster ECSCluster$(stage) --service $(stage)-ms-frontdsh-actores-v1 --force-new-deployment --deployment-configuration minimumHealthyPercent=100,maximumPercent=200 --output json'
      continueOnError: true
